language: ruby
rvm:
- 1.9.3
- 2.0.0
env:
  global:
  - ARTIFACTS_AWS_REGION=us-east-1
  - ARTIFACTS_S3_BUCKET=faktory-artifacts
  - secure: HQqV02P6h2YUAc6YHJ7aNnVOscoMnPtzj6KJbGuE1xishADgnQhBmAU1nQzdA60k624DRFsqmoPeQnSN4AXq+RELXCC98+seWOquCt0ZOYfbNvph3zJNpiFJaqZIilivYvm0AHFA0zie7DIGPnlUNUrmHswukoffgRrDtsXZnLg=
  - secure: LsFz8SWSz0bwtILQzY+VJTPrHP6u6wTO2Y+KTiwcI+h+k4A3+wtnVK4bOBZQ4R2GHB+5s5ZiUxG5b7nXMxxH1+IzY5sWaQVIplVUdErG/YB3o59Xvq7DYsl8Ki13acw2MvmUMOroSb+YrIGUKrJ3H1XpvkwGVx46C7sxCKmcWNg=
before_script:
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 800x600x16
- gem install --version 0.8.0 faraday
- gem install travis-artifacts
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake BROWSER_SIZE=800x600
after_failure:
- travis-artifacts upload
  --path test/kracker/current
  --path test/kracker/diff
  --path tmp/screenshots
  --target-path faktory-artifacts/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER
addons:
  firefox: 19.0.1
